FROM maven:3.6.3
# Note: use specific version to avoid unwanted update
# The version uses redhat linux.

RUN mkdir -p /workdir

# Repo path, $MAVEN_CONFIG=/root/.m2

COPY . /workdir/

EXPOSE 8080
WORKDIR /workdir


# Assumed source directory mounted to workdir
CMD ["/bin/bash", "dockerfiles/runapp"]
